### ISSUE TITLE
Review app code

### ISSUE THREAD

**Issue by Pytlicek** [PostFactum-sk/postfactum-extension#1]
Since I'm not a JS developer and this is my first chrome extension, it would be good if someone will look at the current code base and refactor it if necessary.

The extension works with minimal features. Report a suspicious page and increase or decrease the score of the viewed page.

**Comment by tomtomecek** [comment]
I will take a look at this issue and review the code.

**Comment by Pytlicek** [comment]
Can you look at these resources as well?
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities  

According to the description, it should be quite easy to make this extension to work on both Chrome and Firefox.
Thank you 👍

**Comment by tomtomecek** [comment]
@Pytlicek I will definitely take a look at cross browser extention documentation!
